name: deploy dev

on:
  push:
    branches: [ dev ]

env:
  APP_DEPLOYMENT_STAGE: dev

jobs:
  deploy:
    # this prevents concurrent builds
    concurrency: dev-environment

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # this is required for authenticating to AWS via the OIDC Provider we set up
    permissions:
      id-token: write
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::118674338018:role/GitHubActionsRole
          role-session-name: GithubActionsSession

      - name: npm ci
        run: npm ci

      - name: Build with Webpack
        run: npm build

      - name: run integration test
        run: npm run test

      - name: deploy to dev
        run: npm run deploy

